<a href="https://colab.research.google.com/github/adarsh-one/python-and-numpy-array/blob/main/array_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
Type of data:

1. Primitive = Basic, original, necessary, data types using which more complex data types can be made.

  a. int
  b. float
  c. complex
  d. string
  e. bool

2. Non Primitive = Complex data types, which stores and process large amt. of data and made of several combination of primitive data types.

  a. list
  b. tuple
  c. dict
  d. set

  e. array = stores only single data type data but can store many data of same data types
             all data are sequentially stored in memory
  f. linked list = can store many data of diff data types
                   but all nodes are connected and
                   are not sequentially stored in mem
  g. stacks
  h. queues

  i. trees = stores data in heiarchial structure
             all nodes are linked
             nodes are not sequentially stored in memory
  j. graphs = stores data like dictionary books
              stores data in a network form meaning it will have edges and nodes
              edges and nodes both are neccessary attributes of graphs to perform any functionalities

  ## we have to focus only on array because "numpy" lib is completely based on array
  ## in real word data are stored in table format
     but non primitive data types cannot store in table format
     pandas have advanced data types and stores data in a table format(series and dataframe)
     tables = relational database

  ## list, tuples, set, dict cannot really store huge amount of data and complex data
     therefore,  to overcome that we use new non primitive data type called array

Array(Advancd Non Primitve):

1. Simple , fundamental , most used
2. Similar to (list data type variable) list objects
3. Ordered(Indexed) data type
4. stores multiple values of single data type only
5. useful when need to store large amt. of data wheres list,tuples cannot handle large amt. of data
6. used for effi. memory management because in python arrays are allowed to change type of elements /values stored in array therefore less mem usage but in list this can also be done
7. useful in sorting and searching

Diff. btw. list and array:

1. list = stores multiple value  of multiple data types.
   array = stores multiple value of single date type.
           can store large amount of data
   ## arrays in python only available through "array module" whereas list does not have its separate module
           can store large amount of data

2. list = slower because it stores an additional information i.e, types of its every value since it store values of multiple data types
   arrays = since it only stores single data type values therefore it doesnot need to store type of its value hence faster

3. List = they are more flexible meaning
          can store multiple data type's values
          useful when size of collection can vary dynamically
   arrays = ideal for mathematical computing
            python provides special array called "numpy.array" for mathematical computing

4. list = you cannot change the type of the individual value stored in list sorry wrong you can change data type of individual value
   array = but in numpy array you can change type of individual value eg: from float to int , hence can consume less memory therefore efficient memory management

5. list can be used store many data type values
   but numpy array mostly used to store numerical values for only math computing.


'''


In [ ]:
## Prove that type of individual elements can be changed in list also
lst = [1,3.0,2]

print(type(lst[1]))
print(id(lst))
lst[1] = int(lst[1])

print(type(lst[1]))

print(lst)
print(id(lst))

<class 'float'>
135740457017472
<class 'int'>
[1, 3, 2]
135740457017472


In [ ]:
'''
Python keys/functions/methods

1. Memory usage comparison

   getsizeof() = function
                 require sys module to be imported
                 "import sys"

   to use array in Python we are required to import array module "import array"


Note :  module is basically a package where all the related function to arrays are stored
        import is keyword in python to access any module in existing programme

Note : to access any function from a module eg: array function from array module(ay)
       you need to first call the module everytime (not import) then access array dunction using . op
       eg. new_arr = ay.array()

'''

In [ ]:
## Creating list

lst = [100,200,300,400]
print(lst)
print(type(lst))

[100, 200, 300, 400]
<class 'list'>


In [ ]:
## Creating array

## 1. import array module
import array as arr

## 2. Creating array
##    accessing arr module and from this we are calling array function in it.
##    array function in arr module take 2 args : arr.array('data_type' , list)
new_arr = arr.array('f',[1.1,1.2,1,2])
print(new_arr)
print(type(new_arr))
print(new_arr.dtype)

## here no method called dtype is defined for the objs of class array.array

array('f', [1.100000023841858, 1.2000000476837158, 1.0, 2.0])
<class 'array.array'>


AttributeError: 'array.array' object has no attribute 'dtype'

In [ ]:
'''
This array from array module is of no use for various reasons:
1. when creating array from array module it requires to call an array function and then you need to specify the 1st arg = datatype, and 2nd arg = list
   which is not simple as compared to when we create list

2. when printing it outputs, data type also gets printed and some garbage value in case of decimal numbers
   which is not as simple as when we outputs lists

3. when printing type of array objects of array class in array module , it outputs array.array, what does it means , not easy to understand
   this is not as simple as list type which outputs only list class

4. and many more

Hence we use array from numpy lib

'''

In [2]:
## Creating array using numpy lib/module which has array method/function

import numpy as np

arr_1 = np.array([1,2,3,4])

print(arr_1)
print(type(arr_1))

## new_arr is an object of numpy.ndarray class where array method is defined

## to check data type use obj.dtype method which is only define for numpy.ndarray , this method is not general function

print(arr_1.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int64


In [ ]:
arr_2 = np.array([1.2,1.3,1.4])
print(arr_2)
print(type(arr_2))
print(arr_2.dtype)

[1.2 1.3 1.4]
<class 'numpy.ndarray'>
float64


In [4]:
## diff btw list and array

import sys

lst_ = [100,200,300]
print(lst_)
size_lst = sys.getsizeof(lst_)
print(size_lst)

A = np.array([100,200,300])
print(A)
size_arr = sys.getsizeof(A)
print(size_arr)

[100, 200, 300]
88
[100 200 300]
136


In [ ]:
## ndim = no.of sq outer brackets

In [ ]:
## array traversal

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])

for value in arr:
  if value%2 == 0:
    print(value)

2
4
6
8


In [ ]:
lst = [[1,2],[3,4],[3,3]]

arr2 = np.array(lst)

print(arr2.ndim)

## this way is too good
for x,y in arr2:
  print(x,y)




2
1 2
3 4
3 3


In [ ]:
arr3 = np.array([[9,8,7],[6,5,4],[3,2,1]])

for value in arr3:
  print(value)

for x,y in enumerate(arr3):
  print(x,y)

## look at this, so amazing
for x,y,z in arr3:
  print(x,y,z)


for x,y,z in arr3:
  print(x)
  print(y)
  print(z)

[9 8 7]
[6 5 4]
[3 2 1]
0 [9 8 7]
1 [6 5 4]
2 [3 2 1]
9 8 7
6 5 4
3 2 1
9
8
7
6
5
4
3
2
1


In [ ]:
## np.append(arr, value) function, output a new np.array

arr4 = np.array(["red","yellow","orange"])
arr4.append("pink")

print(arr4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
new_arr = arr4.append("pink")
print(new_arr)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
new_arr = np.append(arr4,"pink")
print(new_arr)


['red' 'yellow' 'orange' 'pink']


In [ ]:
new_arr = np.append(arr4,["mango"])
print(new_arr)

['red' 'yellow' 'orange' 'mango']


In [ ]:
new_arr = np.append(arr4,["pink","mango"])
print(new_arr)

['red' 'yellow' 'orange' 'pink' 'mango']


In [ ]:
## np.concatenate((arr1, arr2/any iterable)), output new np.array
new_arr = np.concatenate((arr4,new_arr))
print(new_arr)

['red' 'yellow' 'orange' 'red' 'yellow' 'orange' 'pink' 'mango']


In [6]:
## As you can see numpy lib is ver compatible with python standard lib, nice
lst1 = ["a","b","c"]

new_arr1 = np.concatenate((lst1,["x","y","z"]))

print(new_arr1)

['a' 'b' 'c' 'x' 'y' 'z']


In [ ]:
## deletion using np.delete(arr, (index1, index2,..)) function in numpy, outputs new np.array
## 2nd argument = index

arr_2 = [100,200,300,400]
new_arr2 = np.delete(arr_2,3)
print(new_arr2)

[100 200 300]


In [ ]:
del new_arr2[2]
print(new_arr2)

ValueError: cannot delete array elements

In [ ]:
## deleting multiple values at the same time
## new_arr = ['red' 'yellow' 'orange' 'red' 'yellow' 'orange' 'pink' 'mango']
new_arr3 = np.delete(new_arr,(0,1))
print(new_arr3)
print(new_arr)

['orange' 'red' 'yellow' 'orange' 'pink' 'mango']
['red' 'yellow' 'orange' 'red' 'yellow' 'orange' 'pink' 'mango']


In [ ]:
## appending multiple values using a iterable
print(arr4)
arr4 = np.append(arr4 , ["pink" , "mango"])
print(arr4)

['red' 'yellow' 'orange']
['red' 'yellow' 'orange' 'pink' 'mango']


In [ ]:
## del using masking

In [7]:
## sorting= obj.sort(), changes the original np.array

n = np.array([1,2,10,2,3,0,7])

n.sort()
print(n)

[ 0  1  2  2  3  7 10]


In [10]:
## descending sorting
n[::-1]
n[::-1].sort()
print(n)

[10  7  3  2  2  1  0]


In [ ]:
## searching
10 in n

True

In [ ]:
## string

## joins is used to combine string elts of a collection
## "delimiter".join(iterable)
st1 = "hello boy"
st2 = "every boy"
lst = st1.split(" ") + st2.split(" ")
new = " ".join(lst)
print(new)

hello boy every boy


In [ ]:
## split() , partition() , find()

st3 = "Life is crazy"
print(st3[-5::])

crazy


In [ ]:
##
## find() , index() , count() , in best

In [ ]:
##

text = " ######@@@@@@get a@@@@@#####         "
text.strip("#@ ")


'get a'

In [14]:
## dynamic array

import numpy as np

a = np.array([])
print(a)

lst = ["how","when","where"]

# Extend the array by concatenating with new elements

for i in lst:
   a = np.concatenate((a, [i]))
   print(a)





[]
['how']
['how' 'when']
['how' 'when' 'where']


In [ ]:
'''
n = eval(input())
diff = abs(n[0]-n[1])
index_1 = 0
index_2 = 1
for i,v in enumerate(n):
    for j in range(i+1,len(n)):
        if abs(v - n[j]) < diff:
          diff = abs(v-n[j])
          index_1 = i
          index_2 = j

lst = [index_1 , index_2]
print(lst)
'''

n = eval(input())

new = sorted(n)


[1,7,9,2,10]
[0, 3]


In [ ]:
## recursion

## base case = how to stop loop
##


def fact(n):

  if n == 0:
    return 1
  else:
    return n*fact(n-1)

In [ ]:
fact(1000)

RecursionError: maximum recursion depth exceeded in comparison

In [15]:
def fib(n):

  if n <= 1:
    return n
  else:
    return fib(n-1)+fib(n-2)

In [16]:
res = fib(6)
print(res)

8


In [ ]:
def sum_lst(lst):
  if len(lst) == 1:
    return lst[0]
  else:
    return lst[0] + sum_lst(lst[1::])

In [ ]:
def trib(n):
  if n <= 1:
    return n
  elif n == 2:
    return 1
  else:
    return trib(n-1)+trib(n-2)+trib(n-3)

In [ ]:
def product_lst(lst):
  if len(lst) == 1:
    return lst[0]
  else:
    return lst[0]*product_lst(lst[1::])


In [ ]:
def pal(string):
  if len(string) == 1:
    return "palindrome"
  elif string[0] != string[-1]:
    return "not palindrome"
  else:
    return pal(string[1:-1])

In [ ]:
def sumdig(n):
  if n < 10:
    return n
  else:
    return n%10 + sumdig(n//10)

In [ ]:
lst = list(eval(input()))
print(type(lst))
print(lst)

1,2,3
<class 'list'>
[1, 2, 3]
